apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: metrics-server
  generatename: ""
  namespace: rbd-system
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: metrics-server
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/metrics-server:v0.3.6
  imagepullpolicy: IfNotPresent
  args: []
  prioritycomponent: false
  env: []
  resources:
    limits: {}
    requests: {}
  volumemounts: []
  volumes: []
status:
  replicas: 0
  readyreplicas: 0
  conditions: []
  pods: []
