apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: nfs-provisioner
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: nfs-provisioner
    priorityComponent: "true"
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/nfs-provisioner:v5.5.0-release
  imagepullpolicy: IfNotPresent
  prioritycomponent: true