apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-chaos
  namespace: rbd-system  
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-chaos
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-chaos:v5.5.0-release
  imagepullpolicy: IfNotPresent
  prioritycomponent: false
