apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-gateway
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-gateway
    priorityComponent: "true"
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-gateway:v5.5.0-release
  imagePullPolicy: IfNotPresent
  priorityComponent: true
