apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-webcli
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-webcli
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-webcli:v5.5.0-release
  imagepullpolicy: IfNotPresent
  prioritycomponent: false
