apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-etcd
  namespace: rbd-system
  labels:
    belongTo: rainbond-operator
    creator: Rainbond
    name: rbd-etcd
    priorityComponent: "true"
spec:
  replicas: 1
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/etcd:v3.3.18
  imagepullpolicy: IfNotPresent
  prioritycomponent: true
