apiVersion: rainbond.io/v1alpha1
kind: RainbondCluster
metadata:
  name: rainbondcluster
  namespace: rbd-system
spec:
  rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
  suffixHTTPHost: d86562.grapps.cn
  gatewayIngressIPs:
  - 192.168.0.58
  nodesForGateway:
  - name: dev002
    internalIP: 192.168.0.58
    externalIP: ""
  nodesForChaos:
  - name: dev002
    internalIP: 192.168.0.58
    externalIP: ""
  installMode: WithoutPackage
  installVersion: v5.5.0-release
  configCompleted: true
  rainbondVolumeSpecRWX:
    csiPlugin:
      nfs: {}
    imageRepository: ""
  cacheMode: hostpath