apiVersion: rainbond.io/v1alpha1
kind: RainbondCluster
metadata:
  name: rainbondcluster
  namespace: rbd-system
spec:
  rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
  suffixHTTPHost: ""
  gatewayIngressIPs:
  - single_node_external_ip
  nodesForGateway:
  - name: single_node_name
    internalIP: single_node_internal_ip
    externalIP: single_node_external_ip
  nodesForChaos:
  - name: single_node_name
    internalIP: single_node_internal_ip
    externalIP: single_node_external_ip
  installMode: WithoutPackage
  installVersion: v5.5.0-release
  configCompleted: true
  cacheMode: hostpath