apiVersion: rainbond.io/v1alpha1
kind: RainbondPackage
metadata:
  name: rainbondpackage
  namespace: rbd-system
  labels: {}
spec:
  pkgPath: /opt/rainbond/pkg/tgz/rainbond.tgz
  imageHubUser: ""
  imageHubPass: ""
