apiVersion: rainbond.io/v1alpha1
kind: RainbondVolume
metadata:
  name: rainbondvolumerwx
  namespace: rbd-system
  labels:
    accessModes: rwx
    belongTo: rainbond-operator
    creator: Rainbond
spec:
  storageClassParameters:
    provisioner: rancher.io/local-path
  imageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
