apiVersion: rainbond.io/v1alpha1
kind: RainbondVolume
metadata:
  name: rainbondvolumerwx
  namespace: rbd-system
  labels:
    accessModes: rwx
    belongTo: rainbond-operator
    creator: Rainbond
spec:
  storageclassname: ""
  storageclassparameters: null
  csiplugin:
    aliyunclouddisk: null
    aliyunnas: null
    nfs: {}
  storagerequest: null
  imagerepository: registry.cn-hangzhou.aliyuncs.com/goodrain
status:
  conditions: []
